name: Node.js CI

on:
  push:
  workflow_dispatch:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: plcking/cicd:latest
          
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.12.1
      uses: actions/setup-node@v1
      with:
        node-version: 18.12.1
    - run: npm install
    - run: CI=false npm run build --if-present
    - run: npm test
    
    
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
     -  name: Create github release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.run_number }}
            release_name: Release ${{ github.run_number }}
        